### ISSUE TITLE
Return coefficient values in DGP library functions in addition to support indices

### ISSUE THREAD

**Issue by tiffanymtang** [Yu-Group/simChef#110]

**Comment by jpdunc23** [comment]
Copied from a comment on closed PR #107 for reference here: We could replace "support" with "beta_nonzero" in return values, which would be some sort of data structure holding the coefficients and their indices at the same time. The package Matrix has sparse vectors and may be worth adding if we have other uses for it (e.g. using sparse matrices). Otherwise, maybe we just create a simple S3 class that replicates `sparseVector`.

**Comment by jpdunc23** [comment]
Moved to `dgpoix`: https://github.com/Yu-Group/dgpoix/issues/2
